README.md

Acknowledge AB3 in README

---

docs/team/tsammeow.md

Add skeletal PPP for tsammeow

---

docs/DeveloperGuide.md

Add definitions to developer guide glossary

---

docs/DeveloperGuide.md

Update DG with add and adddebt use case

---

docs/DeveloperGuide.md

Update DG with statement command

---

.gitignore
docs/DevOps.md
docs/DeveloperGuide.md
src/main/java/paymelah/ui/HelpWindow.java

Refactor all Github/Codecov AB3 links to PayMeLah

---

src/main/java/paymelah/logic/commands/EditCommand.java
src/main/java/paymelah/logic/parser/AddCommandParser.java
src/main/java/paymelah/model/debt/DebtList.java
src/main/java/paymelah/model/debt/exceptions/DebtNotFoundException.java
src/main/java/paymelah/model/person/Person.java
src/main/java/paymelah/model/util/SampleDataUtil.java
src/main/java/paymelah/storage/JsonAdaptedDebt.java
src/main/java/paymelah/storage/JsonAdaptedPerson.java
src/test/java/paymelah/model/debt/DebtListTest.java
src/test/java/paymelah/storage/JsonAdaptedDebtTest.java
src/test/java/paymelah/storage/JsonAdaptedPersonTest.java
src/test/java/paymelah/testutil/DebtListBuilder.java
src/test/java/paymelah/testutil/PersonBuilder.java

Add a list of debts to Person

---

src/main/java/paymelah/model/debt/Debt.java
src/main/java/paymelah/model/util/SampleDataUtil.java
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/paymelah/logic/LogicManagerTest.java
src/test/java/paymelah/logic/commands/CommandTestUtil.java
src/test/java/paymelah/logic/commands/EditCommandTest.java
src/test/java/paymelah/logic/parser/AddCommandParserTest.java
src/test/java/paymelah/testutil/PersonBuilder.java
src/test/java/paymelah/testutil/TypicalDebts.java
src/test/java/paymelah/testutil/TypicalPersons.java

Adds debts to sample data, resolves #72

Debt testability improvements

---

src/test/java/paymelah/testutil/DebtListBuilder.java

Remove default debt from `DebtListBuilder`

---

src/main/java/paymelah/logic/commands/StatementCommand.java
src/main/java/paymelah/logic/parser/AddressBookParser.java
src/main/java/paymelah/model/debt/DebtList.java
src/test/java/paymelah/logic/commands/StatementCommandTest.java

Add statement command

---

src/test/java/paymelah/logic/commands/ClearDebtsCommandTest.java

ClearDebtsCommandTest methods use the Person constructor instead of PersonBuilder. Let's change this.

Fix ClearDebtsCommandTest

---

src/test/java/paymelah/logic/commands/StatementCommandTest.java

Add StatementCommand test cases

---

docs/DeveloperGuide.md

Resolves #47
- At first I wanted to extract listing persons (which exists across several use cases) as a separate use case but then I felt that it was weird since the app lists people by default...

Number use cases

---

docs/DeveloperGuide.md

Update DG on implementation of list debtors feature

---

src/main/java/paymelah/MainApp.java

Update version to 1.3.0

---

docs/DeveloperGuide.md

Add MarkCommand and UnmarkCommand to DG

---

src/main/java/paymelah/logic/parser/AddDebtCommandParser.java
src/main/java/paymelah/logic/parser/SplitDebtCommandParser.java
src/main/java/paymelah/model/debt/Debt.java
src/main/java/paymelah/model/debt/DebtTime.java
src/test/java/paymelah/logic/parser/SplitDebtCommandParserTest.java
src/test/java/paymelah/testutil/DebtBuilder.java

Refactor code to add debt time/date

---

src/main/java/paymelah/model/debt/Money.java
src/test/java/paymelah/model/debt/MoneyTest.java

Enhance Money with service charge, GST calculation

---

src/main/java/paymelah/logic/commands/DeleteDebtCommand.java
src/main/java/paymelah/logic/commands/MarkCommand.java
src/main/java/paymelah/logic/commands/UnmarkCommand.java
src/test/java/paymelah/logic/commands/DeleteDebtCommandTest.java
src/test/java/paymelah/logic/commands/MarkCommandTest.java
src/test/java/paymelah/logic/commands/UnmarkCommandTest.java

Enhance mark/unmark/deletedebt to keep filtered list

---

src/main/java/paymelah/MainApp.java

Update version to 1.3.2

---

src/main/java/paymelah/logic/commands/ListDebtorsCommand.java
src/main/java/paymelah/model/debt/Money.java

Listdebtors without amount specified will no longer list persons with all their debts marked

Fix listdebtors showing persons with all debts marked

---

docs/UserGuide.md

Update UG for adddebt

---

docs/DeveloperGuide.md
docs/UserGuide.md

Bugfix: UG statement and general DG style consistency

---

docs/UserGuide.md

Update general UG formatting errors

---

src/main/java/paymelah/ui/PersonListPanel.java
src/main/resources/view/PersonListCard.fxml

Bugfix: Accordion remember opened tab and add placeholder when no debts for a person

---

src/main/java/paymelah/ui/DebtCard.java

Bugfix: Make isPaid label background smaller than border

---

src/main/java/paymelah/logic/commands/MarkCommand.java
src/main/java/paymelah/logic/commands/UnmarkCommand.java
src/main/java/paymelah/ui/DebtCard.java
src/main/java/paymelah/ui/PersonCard.java

Correct Javadoc mistakes for TheSoggy

---

src/main/java/paymelah/model/person/PersonMatchesDescriptorPredicate.java

This happened when multiple threshold filters on the same field are specified.
Resolves #257

Fix find command not performing AND search on debts

---

docs/UserGuide.md

Clarify finddebt command for user guide

---

docs/DeveloperGuide.md

Update DG effort appendix

---

src/main/java/paymelah/commons/core/Messages.java
src/main/java/paymelah/logic/commands/AddDebtCommand.java
src/main/java/paymelah/model/debt/Money.java

Update correctness of error messages

---

docs/UserGuide.md

Ensure consistency of ellipsis usage in user guide
